/*******************************************************************************
 * The Creative Commons CC-BY-NC 4.0 License
 * http://creativecommons.org/licenses/by-nc/4.0/legalcode
 *
 * Creative Commons (CC) by DFKI GmbH
 * - Vanessa Hahn <Vanessa.Hahn@dfki.de>
 * - Robert Nesselrath <rnesselrath@gmail.com>
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 *******************************************************************************/
/**
 */
package de.dfki.iui.mmds.core.model.io.communicative_functions.provider;

import de.dfki.iui.mmds.core.model.io.communicative_functions.util.Communicative_functionsAdapterFactory;
import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Communicative_functionsItemProviderAdapterFactory extends Communicative_functionsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Communicative_functionsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.SemanticContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticContentItemProvider semanticContentItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.SemanticContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticContentAdapter() {
		if (semanticContentItemProvider == null) {
			semanticContentItemProvider = new SemanticContentItemProvider(this);
		}

		return semanticContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Question} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuestionItemProvider questionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Question}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuestionAdapter() {
		if (questionItemProvider == null) {
			questionItemProvider = new QuestionItemProvider(this);
		}

		return questionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.SetQuestion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetQuestionItemProvider setQuestionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.SetQuestion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetQuestionAdapter() {
		if (setQuestionItemProvider == null) {
			setQuestionItemProvider = new SetQuestionItemProvider(this);
		}

		return setQuestionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveCheckQuestion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveCheckQuestionItemProvider positiveCheckQuestionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveCheckQuestion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveCheckQuestionAdapter() {
		if (positiveCheckQuestionItemProvider == null) {
			positiveCheckQuestionItemProvider = new PositiveCheckQuestionItemProvider(this);
		}

		return positiveCheckQuestionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeCheckQuestion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeCheckQuestionItemProvider negativeCheckQuestionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeCheckQuestion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeCheckQuestionAdapter() {
		if (negativeCheckQuestionItemProvider == null) {
			negativeCheckQuestionItemProvider = new NegativeCheckQuestionItemProvider(this);
		}

		return negativeCheckQuestionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Inform} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InformItemProvider informItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Inform}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInformAdapter() {
		if (informItemProvider == null) {
			informItemProvider = new InformItemProvider(this);
		}

		return informItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Answer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnswerItemProvider answerItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Answer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnswerAdapter() {
		if (answerItemProvider == null) {
			answerItemProvider = new AnswerItemProvider(this);
		}

		return answerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Confirm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfirmItemProvider confirmItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Confirm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfirmAdapter() {
		if (confirmItemProvider == null) {
			confirmItemProvider = new ConfirmItemProvider(this);
		}

		return confirmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Disconfirm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisconfirmItemProvider disconfirmItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Disconfirm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisconfirmAdapter() {
		if (disconfirmItemProvider == null) {
			disconfirmItemProvider = new DisconfirmItemProvider(this);
		}

		return disconfirmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AddressRequest} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressRequestItemProvider addressRequestItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AddressRequest}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressRequestAdapter() {
		if (addressRequestItemProvider == null) {
			addressRequestItemProvider = new AddressRequestItemProvider(this);
		}

		return addressRequestItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AcceptRequest} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AcceptRequestItemProvider acceptRequestItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AcceptRequest}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAcceptRequestAdapter() {
		if (acceptRequestItemProvider == null) {
			acceptRequestItemProvider = new AcceptRequestItemProvider(this);
		}

		return acceptRequestItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.DeclineRequest} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeclineRequestItemProvider declineRequestItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.DeclineRequest}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeclineRequestAdapter() {
		if (declineRequestItemProvider == null) {
			declineRequestItemProvider = new DeclineRequestItemProvider(this);
		}

		return declineRequestItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AcceptSuggestion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AcceptSuggestionItemProvider acceptSuggestionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AcceptSuggestion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAcceptSuggestionAdapter() {
		if (acceptSuggestionItemProvider == null) {
			acceptSuggestionItemProvider = new AcceptSuggestionItemProvider(this);
		}

		return acceptSuggestionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.DeclineSuggestion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeclineSuggestionItemProvider declineSuggestionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.DeclineSuggestion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeclineSuggestionAdapter() {
		if (declineSuggestionItemProvider == null) {
			declineSuggestionItemProvider = new DeclineSuggestionItemProvider(this);
		}

		return declineSuggestionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Request} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequestItemProvider requestItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Request}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequestAdapter() {
		if (requestItemProvider == null) {
			requestItemProvider = new RequestItemProvider(this);
		}

		return requestItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Instruct} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstructItemProvider instructItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Instruct}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInstructAdapter() {
		if (instructItemProvider == null) {
			instructItemProvider = new InstructItemProvider(this);
		}

		return instructItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AddressOffer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddressOfferItemProvider addressOfferItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AddressOffer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddressOfferAdapter() {
		if (addressOfferItemProvider == null) {
			addressOfferItemProvider = new AddressOfferItemProvider(this);
		}

		return addressOfferItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AcceptOffer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AcceptOfferItemProvider acceptOfferItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AcceptOffer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAcceptOfferAdapter() {
		if (acceptOfferItemProvider == null) {
			acceptOfferItemProvider = new AcceptOfferItemProvider(this);
		}

		return acceptOfferItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.DeclineOffer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeclineOfferItemProvider declineOfferItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.DeclineOffer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeclineOfferAdapter() {
		if (declineOfferItemProvider == null) {
			declineOfferItemProvider = new DeclineOfferItemProvider(this);
		}

		return declineOfferItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Suggestion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SuggestionItemProvider suggestionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Suggestion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSuggestionAdapter() {
		if (suggestionItemProvider == null) {
			suggestionItemProvider = new SuggestionItemProvider(this);
		}

		return suggestionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InitialGreeting} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InitialGreetingItemProvider initialGreetingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InitialGreeting}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInitialGreetingAdapter() {
		if (initialGreetingItemProvider == null) {
			initialGreetingItemProvider = new InitialGreetingItemProvider(this);
		}

		return initialGreetingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ReturnGreeting} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnGreetingItemProvider returnGreetingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ReturnGreeting}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnGreetingAdapter() {
		if (returnGreetingItemProvider == null) {
			returnGreetingItemProvider = new ReturnGreetingItemProvider(this);
		}

		return returnGreetingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InitialSelfIntroduction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InitialSelfIntroductionItemProvider initialSelfIntroductionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InitialSelfIntroduction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInitialSelfIntroductionAdapter() {
		if (initialSelfIntroductionItemProvider == null) {
			initialSelfIntroductionItemProvider = new InitialSelfIntroductionItemProvider(this);
		}

		return initialSelfIntroductionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ReturnSelfIntroduction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnSelfIntroductionItemProvider returnSelfIntroductionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ReturnSelfIntroduction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnSelfIntroductionAdapter() {
		if (returnSelfIntroductionItemProvider == null) {
			returnSelfIntroductionItemProvider = new ReturnSelfIntroductionItemProvider(this);
		}

		return returnSelfIntroductionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Apology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApologyItemProvider apologyItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Apology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApologyAdapter() {
		if (apologyItemProvider == null) {
			apologyItemProvider = new ApologyItemProvider(this);
		}

		return apologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ApologyDownplay} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApologyDownplayItemProvider apologyDownplayItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ApologyDownplay}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApologyDownplayAdapter() {
		if (apologyDownplayItemProvider == null) {
			apologyDownplayItemProvider = new ApologyDownplayItemProvider(this);
		}

		return apologyDownplayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Thanking} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThankingItemProvider thankingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Thanking}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThankingAdapter() {
		if (thankingItemProvider == null) {
			thankingItemProvider = new ThankingItemProvider(this);
		}

		return thankingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ThankingDownplay} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThankingDownplayItemProvider thankingDownplayItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ThankingDownplay}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThankingDownplayAdapter() {
		if (thankingDownplayItemProvider == null) {
			thankingDownplayItemProvider = new ThankingDownplayItemProvider(this);
		}

		return thankingDownplayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InitialGoodbye} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InitialGoodbyeItemProvider initialGoodbyeItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InitialGoodbye}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInitialGoodbyeAdapter() {
		if (initialGoodbyeItemProvider == null) {
			initialGoodbyeItemProvider = new InitialGoodbyeItemProvider(this);
		}

		return initialGoodbyeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ReturnGoodbye} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnGoodbyeItemProvider returnGoodbyeItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ReturnGoodbye}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnGoodbyeAdapter() {
		if (returnGoodbyeItemProvider == null) {
			returnGoodbyeItemProvider = new ReturnGoodbyeItemProvider(this);
		}

		return returnGoodbyeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Opening} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpeningItemProvider openingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Opening}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOpeningAdapter() {
		if (openingItemProvider == null) {
			openingItemProvider = new OpeningItemProvider(this);
		}

		return openingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Preclosing} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PreclosingItemProvider preclosingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Preclosing}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPreclosingAdapter() {
		if (preclosingItemProvider == null) {
			preclosingItemProvider = new PreclosingItemProvider(this);
		}

		return preclosingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TopicIntroduction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TopicIntroductionItemProvider topicIntroductionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TopicIntroduction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTopicIntroductionAdapter() {
		if (topicIntroductionItemProvider == null) {
			topicIntroductionItemProvider = new TopicIntroductionItemProvider(this);
		}

		return topicIntroductionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TopicShiftAnnouncement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TopicShiftAnnouncementItemProvider topicShiftAnnouncementItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TopicShiftAnnouncement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTopicShiftAnnouncementAdapter() {
		if (topicShiftAnnouncementItemProvider == null) {
			topicShiftAnnouncementItemProvider = new TopicShiftAnnouncementItemProvider(this);
		}

		return topicShiftAnnouncementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TopicShift} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TopicShiftItemProvider topicShiftItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TopicShift}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTopicShiftAdapter() {
		if (topicShiftItemProvider == null) {
			topicShiftItemProvider = new TopicShiftItemProvider(this);
		}

		return topicShiftItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Completion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompletionItemProvider completionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Completion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompletionAdapter() {
		if (completionItemProvider == null) {
			completionItemProvider = new CompletionItemProvider(this);
		}

		return completionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.CorrectMisspeaking} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CorrectMisspeakingItemProvider correctMisspeakingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.CorrectMisspeaking}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCorrectMisspeakingAdapter() {
		if (correctMisspeakingItemProvider == null) {
			correctMisspeakingItemProvider = new CorrectMisspeakingItemProvider(this);
		}

		return correctMisspeakingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ErrorSignaling} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErrorSignalingItemProvider errorSignalingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ErrorSignaling}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createErrorSignalingAdapter() {
		if (errorSignalingItemProvider == null) {
			errorSignalingItemProvider = new ErrorSignalingItemProvider(this);
		}

		return errorSignalingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Retraction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RetractionItemProvider retractionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Retraction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRetractionAdapter() {
		if (retractionItemProvider == null) {
			retractionItemProvider = new RetractionItemProvider(this);
		}

		return retractionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.SelfCorrection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelfCorrectionItemProvider selfCorrectionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.SelfCorrection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelfCorrectionAdapter() {
		if (selfCorrectionItemProvider == null) {
			selfCorrectionItemProvider = new SelfCorrectionItemProvider(this);
		}

		return selfCorrectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ContactCheck} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContactCheckItemProvider contactCheckItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ContactCheck}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContactCheckAdapter() {
		if (contactCheckItemProvider == null) {
			contactCheckItemProvider = new ContactCheckItemProvider(this);
		}

		return contactCheckItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ContactIndication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContactIndicationItemProvider contactIndicationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ContactIndication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContactIndicationAdapter() {
		if (contactIndicationItemProvider == null) {
			contactIndicationItemProvider = new ContactIndicationItemProvider(this);
		}

		return contactIndicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Stalling} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StallingItemProvider stallingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Stalling}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStallingAdapter() {
		if (stallingItemProvider == null) {
			stallingItemProvider = new StallingItemProvider(this);
		}

		return stallingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Pausing} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PausingItemProvider pausingItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.Pausing}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPausingAdapter() {
		if (pausingItemProvider == null) {
			pausingItemProvider = new PausingItemProvider(this);
		}

		return pausingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnAccept} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnAcceptItemProvider turnAcceptItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnAccept}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnAcceptAdapter() {
		if (turnAcceptItemProvider == null) {
			turnAcceptItemProvider = new TurnAcceptItemProvider(this);
		}

		return turnAcceptItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnGrab} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnGrabItemProvider turnGrabItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnGrab}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnGrabAdapter() {
		if (turnGrabItemProvider == null) {
			turnGrabItemProvider = new TurnGrabItemProvider(this);
		}

		return turnGrabItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnTake} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnTakeItemProvider turnTakeItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnTake}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnTakeAdapter() {
		if (turnTakeItemProvider == null) {
			turnTakeItemProvider = new TurnTakeItemProvider(this);
		}

		return turnTakeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnAssign} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnAssignItemProvider turnAssignItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnAssign}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnAssignAdapter() {
		if (turnAssignItemProvider == null) {
			turnAssignItemProvider = new TurnAssignItemProvider(this);
		}

		return turnAssignItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnKeep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnKeepItemProvider turnKeepItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnKeep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnKeepAdapter() {
		if (turnKeepItemProvider == null) {
			turnKeepItemProvider = new TurnKeepItemProvider(this);
		}

		return turnKeepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnRelease} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnReleaseItemProvider turnReleaseItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.TurnRelease}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnReleaseAdapter() {
		if (turnReleaseItemProvider == null) {
			turnReleaseItemProvider = new TurnReleaseItemProvider(this);
		}

		return turnReleaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AttentionFeedbackElicitation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttentionFeedbackElicitationItemProvider attentionFeedbackElicitationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.AttentionFeedbackElicitation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttentionFeedbackElicitationAdapter() {
		if (attentionFeedbackElicitationItemProvider == null) {
			attentionFeedbackElicitationItemProvider = new AttentionFeedbackElicitationItemProvider(this);
		}

		return attentionFeedbackElicitationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PerceptionFeedbackElicitation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PerceptionFeedbackElicitationItemProvider perceptionFeedbackElicitationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PerceptionFeedbackElicitation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPerceptionFeedbackElicitationAdapter() {
		if (perceptionFeedbackElicitationItemProvider == null) {
			perceptionFeedbackElicitationItemProvider = new PerceptionFeedbackElicitationItemProvider(this);
		}

		return perceptionFeedbackElicitationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InterpretationFeedbackElicitation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterpretationFeedbackElicitationItemProvider interpretationFeedbackElicitationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.InterpretationFeedbackElicitation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterpretationFeedbackElicitationAdapter() {
		if (interpretationFeedbackElicitationItemProvider == null) {
			interpretationFeedbackElicitationItemProvider = new InterpretationFeedbackElicitationItemProvider(this);
		}

		return interpretationFeedbackElicitationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.EvaluationFeedackElicitation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvaluationFeedackElicitationItemProvider evaluationFeedackElicitationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.EvaluationFeedackElicitation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvaluationFeedackElicitationAdapter() {
		if (evaluationFeedackElicitationItemProvider == null) {
			evaluationFeedackElicitationItemProvider = new EvaluationFeedackElicitationItemProvider(this);
		}

		return evaluationFeedackElicitationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ExecutionFeedbackElicitation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExecutionFeedbackElicitationItemProvider executionFeedbackElicitationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.ExecutionFeedbackElicitation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExecutionFeedbackElicitationAdapter() {
		if (executionFeedbackElicitationItemProvider == null) {
			executionFeedbackElicitationItemProvider = new ExecutionFeedbackElicitationItemProvider(this);
		}

		return executionFeedbackElicitationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveAlloFeedbackItemProvider positiveAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveAlloFeedbackAdapter() {
		if (positiveAlloFeedbackItemProvider == null) {
			positiveAlloFeedbackItemProvider = new PositiveAlloFeedbackItemProvider(this);
		}

		return positiveAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeAlloFeedbackItemProvider negativeAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeAlloFeedbackAdapter() {
		if (negativeAlloFeedbackItemProvider == null) {
			negativeAlloFeedbackItemProvider = new NegativeAlloFeedbackItemProvider(this);
		}

		return negativeAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveExecutionAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveExecutionAlloFeedbackItemProvider positiveExecutionAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveExecutionAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveExecutionAlloFeedbackAdapter() {
		if (positiveExecutionAlloFeedbackItemProvider == null) {
			positiveExecutionAlloFeedbackItemProvider = new PositiveExecutionAlloFeedbackItemProvider(this);
		}

		return positiveExecutionAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeExecutionAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeExecutionAlloFeedbackItemProvider negativeExecutionAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeExecutionAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeExecutionAlloFeedbackAdapter() {
		if (negativeExecutionAlloFeedbackItemProvider == null) {
			negativeExecutionAlloFeedbackItemProvider = new NegativeExecutionAlloFeedbackItemProvider(this);
		}

		return negativeExecutionAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveEvaluationAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveEvaluationAlloFeedbackItemProvider positiveEvaluationAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveEvaluationAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveEvaluationAlloFeedbackAdapter() {
		if (positiveEvaluationAlloFeedbackItemProvider == null) {
			positiveEvaluationAlloFeedbackItemProvider = new PositiveEvaluationAlloFeedbackItemProvider(this);
		}

		return positiveEvaluationAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeEvaluationAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeEvaluationAlloFeedbackItemProvider negativeEvaluationAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeEvaluationAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeEvaluationAlloFeedbackAdapter() {
		if (negativeEvaluationAlloFeedbackItemProvider == null) {
			negativeEvaluationAlloFeedbackItemProvider = new NegativeEvaluationAlloFeedbackItemProvider(this);
		}

		return negativeEvaluationAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveInterpretationAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveInterpretationAlloFeedbackItemProvider positiveInterpretationAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveInterpretationAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveInterpretationAlloFeedbackAdapter() {
		if (positiveInterpretationAlloFeedbackItemProvider == null) {
			positiveInterpretationAlloFeedbackItemProvider = new PositiveInterpretationAlloFeedbackItemProvider(this);
		}

		return positiveInterpretationAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeInterpretationAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeInterpretationAlloFeedbackItemProvider negativeInterpretationAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeInterpretationAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeInterpretationAlloFeedbackAdapter() {
		if (negativeInterpretationAlloFeedbackItemProvider == null) {
			negativeInterpretationAlloFeedbackItemProvider = new NegativeInterpretationAlloFeedbackItemProvider(this);
		}

		return negativeInterpretationAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositivePerceptionAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositivePerceptionAlloFeedbackItemProvider positivePerceptionAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositivePerceptionAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositivePerceptionAlloFeedbackAdapter() {
		if (positivePerceptionAlloFeedbackItemProvider == null) {
			positivePerceptionAlloFeedbackItemProvider = new PositivePerceptionAlloFeedbackItemProvider(this);
		}

		return positivePerceptionAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativePerceptionAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativePerceptionAlloFeedbackItemProvider negativePerceptionAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativePerceptionAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativePerceptionAlloFeedbackAdapter() {
		if (negativePerceptionAlloFeedbackItemProvider == null) {
			negativePerceptionAlloFeedbackItemProvider = new NegativePerceptionAlloFeedbackItemProvider(this);
		}

		return negativePerceptionAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAttentionAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeAttentionAlloFeedbackItemProvider negativeAttentionAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAttentionAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeAttentionAlloFeedbackAdapter() {
		if (negativeAttentionAlloFeedbackItemProvider == null) {
			negativeAttentionAlloFeedbackItemProvider = new NegativeAttentionAlloFeedbackItemProvider(this);
		}

		return negativeAttentionAlloFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveAutoFeedbackItemProvider positiveAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveAutoFeedbackAdapter() {
		if (positiveAutoFeedbackItemProvider == null) {
			positiveAutoFeedbackItemProvider = new PositiveAutoFeedbackItemProvider(this);
		}

		return positiveAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeAutoFeedbackItemProvider negativeAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeAutoFeedbackAdapter() {
		if (negativeAutoFeedbackItemProvider == null) {
			negativeAutoFeedbackItemProvider = new NegativeAutoFeedbackItemProvider(this);
		}

		return negativeAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveExecutionAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveExecutionAutoFeedbackItemProvider positiveExecutionAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveExecutionAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveExecutionAutoFeedbackAdapter() {
		if (positiveExecutionAutoFeedbackItemProvider == null) {
			positiveExecutionAutoFeedbackItemProvider = new PositiveExecutionAutoFeedbackItemProvider(this);
		}

		return positiveExecutionAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeExecutionAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeExecutionAutoFeedbackItemProvider negativeExecutionAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeExecutionAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeExecutionAutoFeedbackAdapter() {
		if (negativeExecutionAutoFeedbackItemProvider == null) {
			negativeExecutionAutoFeedbackItemProvider = new NegativeExecutionAutoFeedbackItemProvider(this);
		}

		return negativeExecutionAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveEvaluationAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveEvaluationAutoFeedbackItemProvider positiveEvaluationAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveEvaluationAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveEvaluationAutoFeedbackAdapter() {
		if (positiveEvaluationAutoFeedbackItemProvider == null) {
			positiveEvaluationAutoFeedbackItemProvider = new PositiveEvaluationAutoFeedbackItemProvider(this);
		}

		return positiveEvaluationAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeEvaluationAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeEvaluationAutoFeedbackItemProvider negativeEvaluationAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeEvaluationAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeEvaluationAutoFeedbackAdapter() {
		if (negativeEvaluationAutoFeedbackItemProvider == null) {
			negativeEvaluationAutoFeedbackItemProvider = new NegativeEvaluationAutoFeedbackItemProvider(this);
		}

		return negativeEvaluationAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositivePerceptionAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositivePerceptionAutoFeedbackItemProvider positivePerceptionAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositivePerceptionAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositivePerceptionAutoFeedbackAdapter() {
		if (positivePerceptionAutoFeedbackItemProvider == null) {
			positivePerceptionAutoFeedbackItemProvider = new PositivePerceptionAutoFeedbackItemProvider(this);
		}

		return positivePerceptionAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativePerceptionAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativePerceptionAutoFeedbackItemProvider negativePerceptionAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativePerceptionAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativePerceptionAutoFeedbackAdapter() {
		if (negativePerceptionAutoFeedbackItemProvider == null) {
			negativePerceptionAutoFeedbackItemProvider = new NegativePerceptionAutoFeedbackItemProvider(this);
		}

		return negativePerceptionAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveInterpretationAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveInterpretationAutoFeedbackItemProvider positiveInterpretationAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveInterpretationAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveInterpretationAutoFeedbackAdapter() {
		if (positiveInterpretationAutoFeedbackItemProvider == null) {
			positiveInterpretationAutoFeedbackItemProvider = new PositiveInterpretationAutoFeedbackItemProvider(this);
		}

		return positiveInterpretationAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeInterpretationAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeInterpretationAutoFeedbackItemProvider negativeInterpretationAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeInterpretationAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeInterpretationAutoFeedbackAdapter() {
		if (negativeInterpretationAutoFeedbackItemProvider == null) {
			negativeInterpretationAutoFeedbackItemProvider = new NegativeInterpretationAutoFeedbackItemProvider(this);
		}

		return negativeInterpretationAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAttentionAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveAttentionAutoFeedbackItemProvider positiveAttentionAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAttentionAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveAttentionAutoFeedbackAdapter() {
		if (positiveAttentionAutoFeedbackItemProvider == null) {
			positiveAttentionAutoFeedbackItemProvider = new PositiveAttentionAutoFeedbackItemProvider(this);
		}

		return positiveAttentionAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAttentionAutoFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeAttentionAutoFeedbackItemProvider negativeAttentionAutoFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.NegativeAttentionAutoFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeAttentionAutoFeedbackAdapter() {
		if (negativeAttentionAutoFeedbackItemProvider == null) {
			negativeAttentionAutoFeedbackItemProvider = new NegativeAttentionAutoFeedbackItemProvider(this);
		}

		return negativeAttentionAutoFeedbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAttentionAlloFeedback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositiveAttentionAlloFeedbackItemProvider positiveAttentionAlloFeedbackItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.mmds.core.model.io.communicative_functions.PositiveAttentionAlloFeedback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositiveAttentionAlloFeedbackAdapter() {
		if (positiveAttentionAlloFeedbackItemProvider == null) {
			positiveAttentionAlloFeedbackItemProvider = new PositiveAttentionAlloFeedbackItemProvider(this);
		}

		return positiveAttentionAlloFeedbackItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (semanticContentItemProvider != null) semanticContentItemProvider.dispose();
		if (questionItemProvider != null) questionItemProvider.dispose();
		if (setQuestionItemProvider != null) setQuestionItemProvider.dispose();
		if (positiveCheckQuestionItemProvider != null) positiveCheckQuestionItemProvider.dispose();
		if (negativeCheckQuestionItemProvider != null) negativeCheckQuestionItemProvider.dispose();
		if (informItemProvider != null) informItemProvider.dispose();
		if (answerItemProvider != null) answerItemProvider.dispose();
		if (confirmItemProvider != null) confirmItemProvider.dispose();
		if (disconfirmItemProvider != null) disconfirmItemProvider.dispose();
		if (addressRequestItemProvider != null) addressRequestItemProvider.dispose();
		if (acceptRequestItemProvider != null) acceptRequestItemProvider.dispose();
		if (declineRequestItemProvider != null) declineRequestItemProvider.dispose();
		if (acceptSuggestionItemProvider != null) acceptSuggestionItemProvider.dispose();
		if (declineSuggestionItemProvider != null) declineSuggestionItemProvider.dispose();
		if (requestItemProvider != null) requestItemProvider.dispose();
		if (instructItemProvider != null) instructItemProvider.dispose();
		if (addressOfferItemProvider != null) addressOfferItemProvider.dispose();
		if (acceptOfferItemProvider != null) acceptOfferItemProvider.dispose();
		if (declineOfferItemProvider != null) declineOfferItemProvider.dispose();
		if (suggestionItemProvider != null) suggestionItemProvider.dispose();
		if (initialGreetingItemProvider != null) initialGreetingItemProvider.dispose();
		if (returnGreetingItemProvider != null) returnGreetingItemProvider.dispose();
		if (initialSelfIntroductionItemProvider != null) initialSelfIntroductionItemProvider.dispose();
		if (returnSelfIntroductionItemProvider != null) returnSelfIntroductionItemProvider.dispose();
		if (apologyItemProvider != null) apologyItemProvider.dispose();
		if (apologyDownplayItemProvider != null) apologyDownplayItemProvider.dispose();
		if (thankingItemProvider != null) thankingItemProvider.dispose();
		if (thankingDownplayItemProvider != null) thankingDownplayItemProvider.dispose();
		if (initialGoodbyeItemProvider != null) initialGoodbyeItemProvider.dispose();
		if (returnGoodbyeItemProvider != null) returnGoodbyeItemProvider.dispose();
		if (openingItemProvider != null) openingItemProvider.dispose();
		if (preclosingItemProvider != null) preclosingItemProvider.dispose();
		if (topicIntroductionItemProvider != null) topicIntroductionItemProvider.dispose();
		if (topicShiftAnnouncementItemProvider != null) topicShiftAnnouncementItemProvider.dispose();
		if (topicShiftItemProvider != null) topicShiftItemProvider.dispose();
		if (completionItemProvider != null) completionItemProvider.dispose();
		if (correctMisspeakingItemProvider != null) correctMisspeakingItemProvider.dispose();
		if (errorSignalingItemProvider != null) errorSignalingItemProvider.dispose();
		if (retractionItemProvider != null) retractionItemProvider.dispose();
		if (selfCorrectionItemProvider != null) selfCorrectionItemProvider.dispose();
		if (contactCheckItemProvider != null) contactCheckItemProvider.dispose();
		if (contactIndicationItemProvider != null) contactIndicationItemProvider.dispose();
		if (stallingItemProvider != null) stallingItemProvider.dispose();
		if (pausingItemProvider != null) pausingItemProvider.dispose();
		if (turnAcceptItemProvider != null) turnAcceptItemProvider.dispose();
		if (turnGrabItemProvider != null) turnGrabItemProvider.dispose();
		if (turnTakeItemProvider != null) turnTakeItemProvider.dispose();
		if (turnAssignItemProvider != null) turnAssignItemProvider.dispose();
		if (turnKeepItemProvider != null) turnKeepItemProvider.dispose();
		if (turnReleaseItemProvider != null) turnReleaseItemProvider.dispose();
		if (attentionFeedbackElicitationItemProvider != null) attentionFeedbackElicitationItemProvider.dispose();
		if (perceptionFeedbackElicitationItemProvider != null) perceptionFeedbackElicitationItemProvider.dispose();
		if (interpretationFeedbackElicitationItemProvider != null) interpretationFeedbackElicitationItemProvider.dispose();
		if (evaluationFeedackElicitationItemProvider != null) evaluationFeedackElicitationItemProvider.dispose();
		if (executionFeedbackElicitationItemProvider != null) executionFeedbackElicitationItemProvider.dispose();
		if (positiveAlloFeedbackItemProvider != null) positiveAlloFeedbackItemProvider.dispose();
		if (negativeAlloFeedbackItemProvider != null) negativeAlloFeedbackItemProvider.dispose();
		if (positiveExecutionAlloFeedbackItemProvider != null) positiveExecutionAlloFeedbackItemProvider.dispose();
		if (negativeExecutionAlloFeedbackItemProvider != null) negativeExecutionAlloFeedbackItemProvider.dispose();
		if (positiveEvaluationAlloFeedbackItemProvider != null) positiveEvaluationAlloFeedbackItemProvider.dispose();
		if (negativeEvaluationAlloFeedbackItemProvider != null) negativeEvaluationAlloFeedbackItemProvider.dispose();
		if (positiveInterpretationAlloFeedbackItemProvider != null) positiveInterpretationAlloFeedbackItemProvider.dispose();
		if (negativeInterpretationAlloFeedbackItemProvider != null) negativeInterpretationAlloFeedbackItemProvider.dispose();
		if (positivePerceptionAlloFeedbackItemProvider != null) positivePerceptionAlloFeedbackItemProvider.dispose();
		if (negativePerceptionAlloFeedbackItemProvider != null) negativePerceptionAlloFeedbackItemProvider.dispose();
		if (negativeAttentionAlloFeedbackItemProvider != null) negativeAttentionAlloFeedbackItemProvider.dispose();
		if (positiveAutoFeedbackItemProvider != null) positiveAutoFeedbackItemProvider.dispose();
		if (negativeAutoFeedbackItemProvider != null) negativeAutoFeedbackItemProvider.dispose();
		if (positiveExecutionAutoFeedbackItemProvider != null) positiveExecutionAutoFeedbackItemProvider.dispose();
		if (negativeExecutionAutoFeedbackItemProvider != null) negativeExecutionAutoFeedbackItemProvider.dispose();
		if (positiveEvaluationAutoFeedbackItemProvider != null) positiveEvaluationAutoFeedbackItemProvider.dispose();
		if (negativeEvaluationAutoFeedbackItemProvider != null) negativeEvaluationAutoFeedbackItemProvider.dispose();
		if (positivePerceptionAutoFeedbackItemProvider != null) positivePerceptionAutoFeedbackItemProvider.dispose();
		if (negativePerceptionAutoFeedbackItemProvider != null) negativePerceptionAutoFeedbackItemProvider.dispose();
		if (positiveInterpretationAutoFeedbackItemProvider != null) positiveInterpretationAutoFeedbackItemProvider.dispose();
		if (negativeInterpretationAutoFeedbackItemProvider != null) negativeInterpretationAutoFeedbackItemProvider.dispose();
		if (positiveAttentionAutoFeedbackItemProvider != null) positiveAttentionAutoFeedbackItemProvider.dispose();
		if (negativeAttentionAutoFeedbackItemProvider != null) negativeAttentionAutoFeedbackItemProvider.dispose();
		if (positiveAttentionAlloFeedbackItemProvider != null) positiveAttentionAlloFeedbackItemProvider.dispose();
	}

}
